# Generated by Django 3.1.4 on 2020-12-14 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownTimeJornal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_date_time', models.DateTimeField(verbose_name='Дата-Время начала простоя')),
            ],
            options={
                'verbose_name': 'Начало простоя',
                'verbose_name_plural': 'Журнал простоев',
            },
        ),
        migrations.CreateModel(
            name='GrpStatDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=120, verbose_name='Название группы простоев')),
            ],
            options={
                'verbose_name': 'Название статуса простоя',
                'verbose_name_plural': 'Название статусов простов',
            },
        ),
        migrations.CreateModel(
            name='TechRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_role', models.CharField(max_length=120, verbose_name='Роль техники')),
            ],
            options={
                'verbose_name': 'Роль техники',
                'verbose_name_plural': 'Роли техник',
            },
        ),
        migrations.CreateModel(
            name='TechType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_type', models.CharField(max_length=120, verbose_name='Название типа техники')),
            ],
            options={
                'verbose_name': 'Тип техники',
                'verbose_name_plural': 'Типы техник',
            },
        ),
        migrations.CreateModel(
            name='WorkArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_area', models.CharField(max_length=120, verbose_name='Название объекта (Участка)')),
            ],
            options={
                'verbose_name': 'Объект (Участок)',
                'verbose_name_plural': 'Объекты (Участки)',
            },
        ),
        migrations.CreateModel(
            name='Vinechikle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gar_number', models.CharField(max_length=120, verbose_name='Гаражный номер')),
                ('tech_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.techrole')),
                ('tech_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.techtype')),
                ('work_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workarea')),
            ],
            options={
                'verbose_name': 'Шасси',
                'verbose_name_plural': 'Шасси',
            },
        ),
        migrations.CreateModel(
            name='UpTimeJornal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_date_time', models.DateTimeField(verbose_name='Дата-Время окончание простоя')),
                ('down_time_jornal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.downtimejornal')),
            ],
            options={
                'verbose_name': 'Окончание простоя',
                'verbose_name_plural': 'Журнал окончаний простоев',
            },
        ),
        migrations.CreateModel(
            name='StateDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_1c', models.CharField(blank=True, max_length=120, null=True, verbose_name='Код простоя в 1с')),
                ('name_1c', models.CharField(blank=True, max_length=120, null=True, verbose_name='Имя простоя в 1с')),
                ('name_ASD', models.CharField(blank=True, max_length=120, null=True, verbose_name='Имя простоя в ASD')),
                ('name_ASDv2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Имя простоя в ASD level2')),
                ('shot_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Сокращение простоя')),
                ('grp_stats_down', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.grpstatdown')),
            ],
            options={
                'verbose_name': 'Статус простоя',
                'verbose_name_plural': 'Статусы простоя',
            },
        ),
        migrations.AddField(
            model_name='downtimejornal',
            name='state_down',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.statedown'),
        ),
        migrations.AddField(
            model_name='downtimejornal',
            name='vinechikle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vinechikle'),
        ),
    ]
